=== lucalau00/HOMEWORK-3-LWEB/xml/bali.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="pacchetti_bali">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pacchetto_bali" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id_viaggio" type="xs:integer"/>
              <xs:element name="destinazione" type="xs:string"/>
              <xs:element name="categoria" type="xs:string"/>
              <xs:element name="data_partenza" type="xs:date"/>
              <xs:element name="data_rientro" type="xs:date"/>
              <xs:element name="costo" type="xs:decimal"/>
            </xs:sequence>
            <xs:attribute name="id_bali" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== lucalau00/HOMEWORK-3-LWEB/xml/bali.xml
<?xml version="1.0" encoding="UTF-8"?>
<pacchetti_bali xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="bali.xsd">

  <pacchetto_bali id_bali="1">
    <id_viaggio>2</id_viaggio>
    <destinazione>Bali</destinazione>
    <categoria>low cost</categoria>
    <data_partenza>2027-05-04</data_partenza>
    <data_rientro>2027-05-10</data_rientro>
    <costo>500.00</costo>
  </pacchetto_bali>

</pacchetti_bali>
