=== lucalau00/HOMEWORK-3-LWEB/xml/pagamento.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="pagamenti">

        <xs:complexType>

            <xs:sequence>

                <xs:element
                    name="pagamento"
                    minOccurs="0"
                    maxOccurs="unbounded">

                    <xs:complexType>

                        <xs:sequence>

                            <xs:element
                                name="data"
                                type="xs:date"/>

                            <xs:element
                                name="importo"
                                type="xs:decimal"/>

                            <xs:element
                                name="esito"
                                type="xs:string"/>

                            <xs:element
                                name="id_cliente"
                                type="xs:integer"/>

                        </xs:sequence>

                        <xs:attribute
                            name="id_pagamento"
                            type="xs:integer"
                            use="required"/>

                    </xs:complexType>

                </xs:element>

            </xs:sequence>

        </xs:complexType>

    </xs:element>

</xs:schema>

=== lucalau00/HOMEWORK-3-LWEB/xml/pagamento.xml
<?xml version="1.0" encoding="UTF-8"?>
<pagamenti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="pagamento.xsd">

  <pagamento id_pagamento="11">
    <data>2025-12-06</data>
    <importo>1500.00</importo>
    <esito>approvato</esito>
    <id_cliente>2</id_cliente>
  </pagamento>

  <pagamento id_pagamento="12">
    <data>2025-12-06</data>
    <importo>1000.00</importo>
    <esito>approvato</esito>
    <id_cliente>2</id_cliente>
  </pagamento>

</pagamenti>
